config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :tweets
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tweets, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  has_many :favorites
  has_many :favoritings, through: :favorites, source: :tweet
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_tweets
    Tweet.where(user_id: self.following_ids + [self.id])
  end
  
  def favorite(other_tweet)
    self.favorites.find_or_create_by(tweet_id: other_tweet.id)
  end
  
  def unfavorite(other_tweet)
    favorite = self.favorites.find_by(tweet_id: other_tweet.id)
    favorite.destroy if favorite
  end
  
  def favoriting?(other_tweet)
    self.favoritings.include?(other_tweet)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tweets = user.tweets.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_favorites = user.favorites.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    current_user.favorite(tweet)
    flash[:success] = 'お気に入りに追加しました。'
    redirect_to tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    current_user.unfavorite(tweet)
    flash[:success] = 'お気に入りから削除しました。'
    redirect_to tweets_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = current_user.feed_tweets.order(id: :desc).page(params[:page])
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    #respond_to do |format|
      if @tweet.save
        flash[:success] = 'ツイートを投稿しました。'
        redirect_to tweets_path
        #format.html { redirect_to @tweet }
        #format.json { render :show, status: :created, location: @tweet }
      else
        @tweets = current_user.feed_tweets.order(id: :desc).page(params[:page])
        flash.now[:danger] = 'ツイートを投稿できませんでした。'
        render 'tweets/index'
        #format.html { render :new }
        #format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
      redirect_to tweets_path
    #respond_to do |format|
      #format.html { redirect_to tweets_url }
      #format.json { head :no_content }
    #end
  end

    private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:image, :content)
    end
    
    def correct_user
      @tweet = current_user.tweets.find_by(id: params[:id])
      unless @tweet
        redirect_to root_url
      end
    end
end    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :likes]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def destroy
    @user = User.find(params[:id]) #特定のidを持つ情報を取得
    @user.destroy
    flash[:success] = '退会しました。'
    redirect_to :root #削除に成功すればrootページに戻る
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.favoritings.page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favoriting?(tweet) %>
  <%= form_with(model: current_user.favorites.find_by(tweet_id: tweet.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :tweet_id, tweet.id %>
    <%= f.submit 'Unfavorite', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :tweet_id, tweet.id %>
    <%= f.submit 'Favorite', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">PhotoTwitter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'Other users', users_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
　　　　　　</ul>
　　　　　　<li class="nav-item"><%= link_to "退会", user_path(current_user), method: :delete, data: { confirm: "You sure?" }, class: 'nav-link' %></li>
          </li>
        <% else %>    
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PhotoTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
  <style>
    body {
      background-color: rgb(21, 32, 43);
      color: white;
    }
  </style>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/tweets/_form.html.erb
<style>
  .form-group textarea {
    background-color: rgb(21, 32, 43);
  }
</style>

<%= form_with(model: tweet, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: tweet %>
    <div class="container" style="height: 200px;">
      <div class="form-group">
        <%= form.text_area :content, class: 'form-control', rows: 6, placeholder: "Hello!" %>
      </div>
    
      <div class="row">
        <div class="offset-3 col-2">
        <%= form.file_field :image %>
        </div>
        <div class="col-5 offset-2">
        <%= form.submit 'Tweet', class: 'btn btn-primary' %>
        </div>
      </div>
    </div><br><hr color="white"><hr color="white">
<% end %>

app/views/tweets/_tweets.html.erb
<style>
  .tweet_image {
    width: 500px;
  }
  
  #wrapper {
    display: flex;
    justify-content: space-between;
  }
  
  p.w-nomal {
    width: 300px;
    word-wrap: normal;
  }
  
  .content {
    margin: auto;
  }
</style>

<ul class="list-unstyled">
  <% tweets.each do |tweet| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(tweet.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to tweet.user.name, user_path(tweet.user) %> <span class="text-muted">posted at <%= tweet.created_at %></span>
        </div>
        <div id="wrapper">
          <p class="mb-0"><%= image_tag tweet.image.url, class: "tweet_image" %></p>
          
          <div class="content">
            <p class="w-nomal"><%= tweet.content.gsub(/\r\n|\r|\n/, "<br>").html_safe %></p>
          </div>
          
        </div>
        <div class="container">
          <div class="row">
            <div class="offset-8 col-md-1">
              <%= render 'favorites/favorite_button', tweet: tweet %>
            </div>
            <div class="col-md-1">
              <% if current_user == tweet.user %>
                <%= link_to "Delete", tweet, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </div>
          </div>
        </div><hr color="white">  
    </li>
  <% end %>
  <%= paginate tweets %>
</ul>

app/views/tweets/index.html.erb
<% if logged_in? %>

<%= render 'tweets/form', tweet: @tweet %>
<hr>
<div>
  <%= render 'tweets/tweets', tweets: @tweets %>
</div>

<% else %>
  <%= render partial: 'sessions/new' %>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/followers.html.erb
<div class="container" style="height: 300px;">
  <div class="row">
    <div class="col-3">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="col-9">
      <h1 style="color: white; text-align: center; margin-top: 50px;"><%= @user.name %></h1>
    </div>
  </div>
  <br>
  <div>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
  <button><%= link_to 'Back', user_path(current_user) %></button>
</div>

app/views/users/followings.html.erb
<div class="container" style="height: 300px;">
  <div class="row">
    <div class="col-3">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="col-9">
      <h1 style="color: white; text-align: center; margin-top: 50px;"><%= @user.name %></h1>
    </div>
  </div>
  <br>
  <div>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
  <button><%= link_to 'Back', user_path(current_user) %></button>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="container" style="height: 300px;">
  <div class="row">
    <div class="col-3">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
    </div>
    <div class="col-9">
      <h1 style="text-align: center; margin-top: 50px;"><%= @user.name %></h1>
    </div>
  </div>
  <a href="<%= followings_user_path(@user) %>"> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a>
  <a href="<%= followers_user_path(@user) %>"> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a>
</div>
<%= render 'relationships/follow_button', user: @user %>
<div>
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Tweets <span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
    <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
  </ul>
  <%= render 'tweets/tweets', tweets: @likes %>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Signup</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'password confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'signup', class: 'btn btn-primary btn-block' %>
      <%= link_to 'Login', login_path %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" style="height: 300px;">
  <div class="row">
    <div class="col-3">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="col-9">
      <h1 style="color: white; text-align: center; margin-top: 100px;"><%= @user.name %></h1>
    </div>
  </div>
  <a href="<%= followings_user_path(@user) %>"> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a>
  <a href="<%= followers_user_path(@user) %>"> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a>
</div>
<br>
<div>
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Tweets <span class="badge badge-secondary"><%= @count_tweets %></span></a></li>
    <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
  </ul>
  <%= render 'tweets/tweets', tweets: @tweets %>
</div>